import { gql } from '@urql/core';
import { GasPriceInfo } from './nodes/gasPriceInfo';

// TODO: Add order direction when we figure out how to handle the enums generated by codegen
export const GasPrice = gql`
  fragment GasPrice on EVMSchemaType {
    gasPrices(filter: $filter) {
      ...GasPriceInfo
    }
  }
  ${GasPriceInfo}
`;
