name: upload test coverage to coveralls
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags.

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm ci

      - name: Run Test Coverage
        run: nx run libs-sdk:test-coverage

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1
        with:
          file: packages/libs/sdk/coverage/lcov.info
